apiVersion: v1
kind: Endpoints
metadata:
  name: external-gateway
  namespace: monitoring   
  labels:
    app: external-gateway
subsets:
- addresses:
  - ip: 158.247.230.158   # 팀원 서버 IP
  ports:
  - name: web-port
    port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: external-gateway
  namespace: monitoring   
  labels:
    app: external-gateway
spec:
  ports:
  - name: web-port
    port: 80
    targetPort: 80
  clusterIP: None

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-gateway-monitor
  namespace: monitoring
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: external-gateway
  namespaceSelector:
    matchNames:
    - monitoring   
  endpoints:
  - port: web-port
    path: /metrics
    interval: 15s