apiVersion: v1
kind: Service
metadata:
  name: kibana-lb
  namespace: elk
spec:
  type: LoadBalancer
  loadBalancerIP: 34.123.45.67
  selector:
    kibana.k8s.elastic.co/name: kibana
  ports:
    - name: https
      port: 443
      targetPort: 5601
